# Generated by Django 5.0.4 on 2024-05-09 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rooms_user_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
