# Generated by Django 5.0.4 on 2024-05-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_rooms_user_rooms_assign_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='assign_user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
