# Generated by Django 5.0.4 on 2024-05-10 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_rooms_assign_user_id_delete_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='assign_user_id',
        ),
        migrations.AddField(
            model_name='rooms',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
